### ISSUE TITLE
Search button timeout is very short

### ISSUE THREAD

**Issue by andygup** [Esri/nearby-javascript#19]
I'm not sure about the use case(s) for having a short timeout. I suggest bumping the Notification.tsx snackbar timeout from 3000 to something like 10000, or longer.

**Comment by odoe** [comment]
I don't know if there is enough header space for another button on a mobile device without being too cluttered. I can work on some ideas though.

**Comment by odoe** [comment]
fixed in https://github.com/Esri/nearby-javascript/commit/02f76cdc1ca86e5217591be9ccf394f2dd762f61

**Comment by andygup** [comment]
LGTM, much better.
