### ISSUE TITLE
Not sure how filter is supposed to work?

### ISSUE THREAD

**Issue by andygup** [Esri/nearby-javascript#23]
How is the filter supposed to work? It seems like it reorders the list somewhat inconsistently. Is it supposed to only display results based on that keyword? 

Here's an example where I selected filter by "Pizza" 

![image](https://user-images.githubusercontent.com/510440/53053473-b03f0100-345e-11e9-9863-f4b871ad7578.png)

And, the same list when filtered by "Hotel"

![image](https://user-images.githubusercontent.com/510440/53053526-dd8baf00-345e-11e9-97d1-3fe52145d470.png)

This is filtered by "Coffee Shops", the hotel is still at the top of the list:

![image](https://user-images.githubusercontent.com/510440/53053750-791d1f80-345f-11e9-9ad3-43958b2af4c4.png)

**Comment by odoe** [comment]
There is some discussion on this in #8.

You can look under the _Supported category values_ on [this page](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-category-filtering.htm).

`Food` is a category 2 value.
`Pizza` is a category 3 value.

All `Pizza` is a `Food`, but not all `Food` is a `Pizza`, if that makes sense.

When the category filters are updated, the request is sent back to the geocoding REST API and the results are shown as given. I don't resort or change them in any way.

**Comment by andygup** [comment]
@odoe Thanks, yep I get the sub-categories. My expectation is there should only be a single, top-level category requested when applying the filter. The app is generating multiple categories per filter-based request. That seems like a bug?

Reference: https://developers.arcgis.com/rest/geocode/api-reference/geocoding-category-filtering.htm => Category Request Details.

Example 1: When I select "Hotel", here's what I'm seeing in the `findAddressCandidates` request header:

```
category: Coffee Shop,Hotel
// My expectation => category: Hotel
```

Example [findAddressCandidates](https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?f=json&outFields=Place_addr%2CPlaceName%2CPhone%2CURL%2CType&category=Hotel&distance=50&location=%7B%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%2C%22x%22%3A-105.20124999999818%2C%22y%22%3A40.06995999999937%7D&maxLocations=20) request with a single category

When I select "Pizza":

```
category: Coffee Shop,Pizza,Hotel
// My expectation => category: Pizza
```

And when I select "Food":

```
category: Coffee Shop,Food,Pizza,Hotel
// My expectation => category: Food
```

**Comment by andygup** [comment]
OHHHH, you have to de-select filters! That wasn't intuitive.

**Comment by mikewilburn** [comment]
@andygup this was my first thought when I saw this issue pop up. Glad we don't have any bugs here!
Yes, you must de-select the category filters to update the POIs shown on the map & in the list. By default, they're all enabled.

**Comment by odoe** [comment]
I think we're ok on this one @andygup
