### ISSUE TITLE
Tests fail and app do not compile

### ISSUE THREAD

**Issue by gozieaf** [Esri/nearby-javascript#32]
I ran ```npm test`` and I could not get all tests to run successfully. Here is a screenshot of the error messages I am getting
![image](https://user-images.githubusercontent.com/39274163/95005073-7139d100-05eb-11eb-9a18-fd88c63c7302.png)
Also, the app doesn't compile when I run npm start What do I do next to resolve this?

**Comment by gozieaf** [comment]
Issue has been resolved. It was due to machine location variability.

**Comment by odoe** [comment]
There will be an update to this app coming in the next or two for ArcGIS API for JS 4.17, and this should resolve these issues. Thanks.
