### ISSUE TITLE
Map doesn't load on first app load

### ISSUE THREAD

**Issue by codergrl** [Esri/nearby-javascript#6]
I loaded the app and got a list of nearby places (see issue #5 for screenshot). Then I clicked on the Map button and a globe flashed for a split second but then the page just went blank. I refreshed it after about 10 minutes of waiting and then it loaded. Cleared cache and retried, same behavior, the map didn't load until I refreshed it

Device: Microsoft Surface 3
OS: Windows 10 version 1803 build 17134
Browser: Chrome v. 71.0.3578.98

**Comment by mikewilburn** [comment]
Closing. No longer an issue with the app itself.
